## Change the name of this file to application-prod-mysql.yml for production
## or to application-devel-mysql.yml for development with mysql

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/recipe
        username: recipe_client
        password: password
        platform: mysql
        testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
        validationQuery: SELECT 1 # Keep the connection alive if idle for a long time (needed in production)
    jpa:
        hibernate.ddl-auto: none # Set to validate for production
        database-platform: org.hibernate.dialect.MySQL5Dialect
        database: mysql
        show-sql: true # Set to false for production
        hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        properties.javax.persistence.schema-generation:
            create-source: metadata
            scripts:
              action: none # For script-generation set to: drop-and-create - One done set to: none
              create-target: Docker/mysql/create.sql
              drop-target: Docker/mysql/drop.sql