recipes.quickRecipes.MaxDuration: 30

spring:
# spring.profiles.active possible values are: devel-mysql, devel-h2, prod-mysql
    profiles.active: devel-mysql
    config.additional-location: classpath*:config/

logging.level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    com.tomlouiskeller.recipe: DEBUG


# spring.profiles.active chooses application-{profile}.yml