recipes.quickRecipes.MaxDuration: 30

# Set development or production in "environment" and "spring.profiles.active"
environment: development

spring:
    profiles.active: development # For some reason variables don't work for spring.profiles.active, so we have to set it again.
    datasource.platform: ${environment}
    datasource.schema: classpath*:config/${environment}/schema.sql
    datasource.data: classpath*:config/${environment}/data.sql
    config.additional-location: classpath*:config/${environment}/

logging.level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    com.tomlouiskeller: DEBUG